*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 13.07.2018 at 11:54:35
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: /DMF/BP_SUB_T_V.................................*
FORM GET_DATA_/DMF/BP_SUB_T_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM /DMF/BP_SUB_T WHERE
(VIM_WHERETAB) .
    CLEAR /DMF/BP_SUB_T_V .
/DMF/BP_SUB_T_V-MANDT =
/DMF/BP_SUB_T-MANDT .
/DMF/BP_SUB_T_V-LANGU =
/DMF/BP_SUB_T-LANGU .
/DMF/BP_SUB_T_V-BP_SUBTYPE =
/DMF/BP_SUB_T-BP_SUBTYPE .
/DMF/BP_SUB_T_V-VTEXT =
/DMF/BP_SUB_T-VTEXT .
<VIM_TOTAL_STRUC> = /DMF/BP_SUB_T_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_/DMF/BP_SUB_T_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO /DMF/BP_SUB_T_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_/DMF/BP_SUB_T_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM /DMF/BP_SUB_T WHERE
  LANGU = /DMF/BP_SUB_T_V-LANGU AND
  BP_SUBTYPE = /DMF/BP_SUB_T_V-BP_SUBTYPE .
    IF SY-SUBRC = 0.
    DELETE /DMF/BP_SUB_T .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM /DMF/BP_SUB_T WHERE
  LANGU = /DMF/BP_SUB_T_V-LANGU AND
  BP_SUBTYPE = /DMF/BP_SUB_T_V-BP_SUBTYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR /DMF/BP_SUB_T.
    ENDIF.
/DMF/BP_SUB_T-MANDT =
/DMF/BP_SUB_T_V-MANDT .
/DMF/BP_SUB_T-LANGU =
/DMF/BP_SUB_T_V-LANGU .
/DMF/BP_SUB_T-BP_SUBTYPE =
/DMF/BP_SUB_T_V-BP_SUBTYPE .
/DMF/BP_SUB_T-VTEXT =
/DMF/BP_SUB_T_V-VTEXT .
    IF SY-SUBRC = 0.
    UPDATE /DMF/BP_SUB_T ##WARN_OK.
    ELSE.
    INSERT /DMF/BP_SUB_T .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_/DMF/BP_SUB_T_V-UPD_FLAG,
STATUS_/DMF/BP_SUB_T_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_/DMF/BP_SUB_T_V.
  SELECT SINGLE * FROM /DMF/BP_SUB_T WHERE
LANGU = /DMF/BP_SUB_T_V-LANGU AND
BP_SUBTYPE = /DMF/BP_SUB_T_V-BP_SUBTYPE .
/DMF/BP_SUB_T_V-MANDT =
/DMF/BP_SUB_T-MANDT .
/DMF/BP_SUB_T_V-LANGU =
/DMF/BP_SUB_T-LANGU .
/DMF/BP_SUB_T_V-BP_SUBTYPE =
/DMF/BP_SUB_T-BP_SUBTYPE .
/DMF/BP_SUB_T_V-VTEXT =
/DMF/BP_SUB_T-VTEXT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_/DMF/BP_SUB_T_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE /DMF/BP_SUB_T_V-LANGU TO
/DMF/BP_SUB_T-LANGU .
MOVE /DMF/BP_SUB_T_V-BP_SUBTYPE TO
/DMF/BP_SUB_T-BP_SUBTYPE .
MOVE /DMF/BP_SUB_T_V-MANDT TO
/DMF/BP_SUB_T-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = '/DMF/BP_SUB_T'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN /DMF/BP_SUB_T TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING '/DMF/BP_SUB_T'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
